name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the version of Node.js you need

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build --prod

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/ng_portfolio/browser  # Adjust this path to match your built Angular app directory
        server-dir: /public_html  # Adjust this path if your hosting structure is different
